### PR TITLE
Adding comma dangle rule and fixing eslint issues

### PR DESCRIPTION
**Pull request by mattsibs**
- Comma dangle causes following issue for angular builds
  "Unexpected token: punc ()) angular"
This is due to comma dangle in source files

### CODE REVIEW

**Comment by erikbrinkman** [comment]
I looks like you modified the eslint config, but not the prettier config. The project is formatted with prettier, so unfortunately the commas spec needs to be changed twice. Unfortunately I didn't actually have a check to make sure that things are properly formatted. If you rebase onto master, the tests should now fail because you didn't update the prettier config.

The resolution should be simple enough, edit the `.prettierrc.toml` to say `trailingComma = "es5"` (I think that should be the level you want for angular. There's also `"none"`, but I think that's overkill. Then just run `npm run format` and update the pr.

**Comment by mattsibs** [comment]
@erikbrinkman I have updated the prettier config and run the formatter

**Comment by mattsibs** [comment]
The only way to make the linting rules pass was to add the trailingComma='none' format setting

**Comment by erikbrinkman** [comment]
Everything looks great. Can you rebase on top of master first and make sure that tests pass?

**Comment by mattsibs** [comment]
> Everything looks great. Can you rebase on top of master first and make sure that tests pass?
> 
> Sorry I'm being such a pedant about this.

The branch is up to date with master and all tests pass 😺 ive run them locally just to be sure. Does the travis build run them as well?

**Comment by mattsibs** [comment]
@erikbrinkman  yep sorry im with you, rebased and pushed :)

**Pull request merged**
